apiVersion: v1
kind: Service
metadata:
  name: deis-controller
  labels:
    heritage: deis
    router.deis.cc/routable: "true"
  annotations:
    router.deis.cc/domains: deis
    router.deis.cc/connectTimeout: "10"
    router.deis.cc/tcpTimeout: "1200"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: deis-controller
